version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: companyservicedb
    environment:
      POSTGRES_DB: company_db_2
      POSTGRES_USER: actual_username
      POSTGRES_PASSWORD: actual_password
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U actual_username"]
      interval: 15s
      timeout: 10s
      retries: 10

  company:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: companyservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://companyservicedb:5432/company_db_2
      SPRING_DATASOURCE_USERNAME: actual_username
      SPRING_DATASOURCE_PASSWORD: actual_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

